
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.bitflags]]
version = "2.13.2"
criteria = "safe-to-deploy"

[[exemptions.camino]]
version = "1.2.6"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.189"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.pulldown-cmark]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.pulldown-cmark-escape]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "1.1.5"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"
